In [2]:
import tensorflow as tf

# Creating Tensors

In [3]:
string = tf.Variable("hey", tf.string)
number = tf.Variable(16, tf.int16)
floating = tf.Variable(3.1415, tf.float64)

### Rank: number of dimensions
- rank 0 is a scalar
- rank 1 is a 1-d vector (1 direction or 1 list)

In [4]:
rank1_tensor = tf.Variable(["test", "ok", "tim"], tf.string)
rank1 = tf.rank(rank1_tensor)
shape1 = rank1_tensor.shape

print(rank1)
print(shape1)

tf.Tensor(1, shape=(), dtype=int32)
(3,)


In [5]:
rank2_tensor = tf.Variable([["test", "ok"], ["test", "tim"]], tf.string)
rank2 = tf.rank(rank2_tensor)
shape2 = rank2_tensor.shape

print(rank2)
print(shape2) ## 2 lists, 2 elements per list

tf.Tensor(2, shape=(), dtype=int32)
(2, 2)


# Reshaping Tensors

In [6]:
tensor1 = tf.ones([1,2,3]) ##gives us 1's, in shape [1,2,3]
tensor2 = tf.reshape(tensor1, [2,3,1])
tensor3 = tf.reshape(tensor2, [3,-1]) ##-1 tells to guess the second dimension size. will ive [3,2] in this instance.


In [7]:
print(tensor1)
print(tensor2)
print(tensor3)

tf.Tensor(
[[[1. 1. 1.]
  [1. 1. 1.]]], shape=(1, 2, 3), dtype=float32)
tf.Tensor(
[[[1.]
  [1.]
  [1.]]

 [[1.]
  [1.]
  [1.]]], shape=(2, 3, 1), dtype=float32)
tf.Tensor(
[[1. 1.]
 [1. 1.]
 [1. 1.]], shape=(3, 2), dtype=float32)


### Types of Tensors
- Variable*
- Constant
- Placeholder
- SparseTensor

All of these tensors are immutable with the exception of the Variable tensor. So, we use Variable tensor when we know we will want to change certain values in a tensor.

### TensorFlow Functions (2.0)
Using @tf.function allows us to convert a python function into a TensorFlow graph and optimize the performance of the function. Executing a function involving tf variables is called "eager execution"


In [9]:
@tf.function
def matmul(a, b):
    return tf.matmul(a, b)

# Perform the operation using the defined function
result = matmul(tensor1, tensor2)
print(result.numpy())

[[[3.]
  [3.]]

 [[3.]
  [3.]]]


# Reshaping Practice
Note: to get number of elements in a matrix, just multiply the dimensions (given by the shape).

In [17]:
t = tf.zeros([5,5,5,5])
print(t)

t = tf.reshape(t, [625])
print(t)

t = tf.reshape(t, [125, -1]) #here, program infers a shape of [125,5]
print(t)
print(t.shape)

tf.Tensor(
[[[[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]]


 [[[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0.